In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r'E:\Aroha Tech\Pandas Session\Data_Outlet.csv')

In [5]:
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

find 2nd highest Item_Outlet_Sales in each Outlet_type

In [61]:
oltr=df.groupby('Outlet_Type').max('Item_Outlet_Sales')
oltr['Item_Outlet_Sales']

Outlet_Type
Grocery Store         1775.6886
Supermarket Type1    10256.6490
Supermarket Type2     6768.5228
Supermarket Type3    13086.9648
Name: Item_Outlet_Sales, dtype: float64

In [50]:
acd=df.groupby('Outlet_Type').apply(lambda x : x[x['Item_Outlet_Sales']<x['Item_Outlet_Sales'].max()].max())

In [53]:
acd

Outlet_Type
Grocery Store      Item_Identifier                          NCZ54
                   Item_Weight                              21.35
                   Item_Fat_Content                           reg
                   Item_Visibility                       0.328391
                   Item_Type                        Starchy Foods
                   Item_MRP                              266.6884
                   Outlet_Identifier                       OUT019
                   Outlet_Establishment_Year                 1998
                   Outlet_Location_Type                    Tier 3
                   Outlet_Type                      Grocery Store
                   Item_Outlet_Sales                    1575.2828
Supermarket Type1  Item_Identifier                          NCZ54
                   Item_Weight                              21.35
                   Item_Fat_Content                           reg
                   Item_Visibility                        0.18862
                   Item_Type                        Starchy Foods
                   Item_MRP                              266.8884
                   Outlet_Identifier                       OUT049
                   Outlet_Establishment_Year                 2007
                   Outlet_Location_Type                    Tier 3
                   Outlet_Type                  Supermarket Type1
                   Item_Outlet_Sales                    9779.9362
Supermarket Type2  Item_Identifier                          NCZ54
                   Item_Weight                              21.35
                   Item_Fat_Content                           reg
                   Item_Visibility                       0.188323
                   Item_Type                        Starchy Foods
                   Item_MRP                              265.1884
                   Outlet_Identifier                       OUT018
                   Outlet_Establishment_Year                 2009
                   Outlet_Size                             Medium
                   Outlet_Location_Type                    Tier 3
                   Outlet_Type                  Supermarket Type2
                   Item_Outlet_Sales                    6729.9064
Supermarket Type3  Item_Identifier                          NCZ54
                   Item_Weight                                NaN
                   Item_Fat_Content                           reg
                   Item_Visibility                       0.183948
                   Item_Type                        Starchy Foods
                   Item_MRP                              265.2884
                   Outlet_Identifier                       OUT027
                   Outlet_Establishment_Year                 1985
                   Outlet_Size                             Medium
                   Outlet_Location_Type                    Tier 3
                   Outlet_Type                  Supermarket Type3
                   Item_Outlet_Sales                     12117.56
dtype: object

Fill nan value of Item_visibility  with average value of each item_type in apropriate position

In [97]:
avg_val=df.groupby('Item_Type')

In [100]:
mean('Item_Visibility')

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
Item_Type,,,,,
Baking Goods,12.277108,0.069169,126.380766,1997.728395,1952.971207
Breads,11.346936,0.066255,140.952669,1997.657371,2204.132226
Breakfast,12.768202,0.085723,141.788151,1997.336364,2111.808651
Canned,12.305705,0.068129,139.763832,1998.152542,2225.194904
Dairy,13.426069,0.072427,148.499208,1997.681818,2232.542597
Frozen Foods,12.867061,0.065645,138.503366,1998.024533,2132.867744
Fruits and Vegetables,13.224769,0.068513,144.581235,1997.719968,2289.009592
Hard Drinks,11.400328,0.064943,137.077928,1998.177570,2139.221622
Health and Hygiene,13.142314,0.055216,130.818921,1997.734615,2010.000265
Household,13.384736,0.061322,149.424753,1997.784615,2258.784300
Meat,12.817344,0.062284,139.882032,1997.341176,2158.977911
Others,13.853285,0.060241,132.851430,1997.662722,1926.139702
Seafood,12.552843,0.074976,141.841719,1997.734375,2326.065928
Snack Foods,12.987880,0.066850,146.194934,1997.886667,2277.321739
Soft Drinks,11.847460,0.063972,131.492506,1998.098876,2006.511735
Starchy Foods,13.690731,0.067564,147.838023,1998.581081,2374.332773

Based on Outlet_Identifier find how many item_types are there in a perticular Outlet_Identifier

In [47]:
oti=df['Outlet_Identifier'].value_counts()

In [48]:
oti

OUT027    935
OUT013    932
OUT046    930
OUT035    930
OUT049    930
OUT045    929
OUT018    928
OUT017    926
OUT010    555
OUT019    528
Name: Outlet_Identifier, dtype: int64

In [42]:
for i in oti.index:
    print(i)
    ot=df['Outlet_Identifier']==i
    print(df.loc[ot]['Item_Type'].value_counts())

OUT027
Fruits and Vegetables    140
Snack Foods              137
Household                 99
Frozen Foods              89
Canned                    72
Baking Goods              69
Dairy                     67
Health and Hygiene        60
Meat                      56
Soft Drinks               45
Breads                    31
Hard Drinks               23
Others                    15
Starchy Foods             14
Breakfast                 11
Seafood                    7
Name: Item_Type, dtype: int64
OUT013
Fruits and Vegetables    142
Snack Foods              125
Household                103
Frozen Foods              92
Dairy                     80
Baking Goods              73
Canned                    65
Health and Hygiene        61
Soft Drinks               49
Meat                      41
Breads                    25
Hard Drinks               23
Starchy Foods             19
Others                    16
Breakfast                 13
Seafood                    5
Name: Item_Type, dtype: int64
OUT046
Fruits and Vegetables    126
Snack Foods              120
Frozen Foods             108
Household                103
Dairy                     78
Baking Goods              76
Canned                    72
Health and Hygiene        56
Soft Drinks               48
Meat                      44
Breads                    26
Others                    22
Hard Drinks               20
Starchy Foods             15
Breakfast                 10
Seafood                    6
Name: Item_Type, dtype: int64
OUT035
Snack Foods              140
Fruits and Vegetables    129
Household                102
Frozen Foods              92
Canned                    79
Dairy                     71
Baking Goods              68
Soft Drinks               52
Health and Hygiene        50
Meat                      43
Breads                    29
Hard Drinks               22
Starchy Foods             19
Others                    16
Breakfast                 10
Seafood                    8
Name: Item_Type, dtype: int64
OUT049
Snack Foods              139
Fruits and Vegetables    138
Household                 95
Frozen Foods              93
Dairy                     78
Canned                    67
Baking Goods              66
Health and Hygiene        52
Meat                      47
Soft Drinks               46
Hard Drinks               30
Breads                    25
Starchy Foods             17
Others                    17
Breakfast                 13
Seafood                    7
Name: Item_Type, dtype: int64
OUT045
Fruits and Vegetables    143
Snack Foods              133
Household                 99
Frozen Foods              81
Canned                    74
Baking Goods              70
Dairy                     69
Health and Hygiene        55
Soft Drinks               51
Meat                      38
Breads                    33
Hard Drinks               28
Others                    20
Starchy Foods             16
Breakfast                 10
Seafood                    9
Name: Item_Type, dtype: int64
OUT018
Fruits and Vegetables    135
Snack Foods              132
Household                 95
Frozen Foods              92
Canned                    78
Dairy                     73
Baking Goods              68
Health and Hygiene        58
Soft Drinks               46
Meat                      46
Breads                    27
Hard Drinks               22
Others                    20
Starchy Foods             17
Breakfast                 12
Seafood                    7
Name: Item_Type, dtype: int64
OUT017
Snack Foods              128
Fruits and Vegetables    127
Frozen Foods             106
Household                 95
Dairy                     74
Baking Goods              73
Canned                    69
Health and Hygiene        61
Soft Drinks               54
Meat                      44
Breads                    22
Hard Drinks               22
Starchy Foods             18
Others                    16
Breakfast                 12
Seafood                    5
Name: Item_Type, dtype: int64
OUT010
Fruits and Vegetables    79
Snack Foods              71
Household                67
Frozen Foods             54
Dairy                    43
Baking Goods             42
Health and Hygiene       37
Canned                   35
Meat                     34
Soft Drinks              28
Breads                   17
Hard Drinks              16
Others                   10
Starchy Foods             9
Breakfast                 9
Seafood                   4
Name: Item_Type, dtype: int64
OUT019
Snack Foods              75
Fruits and Vegetables    73
Household                52
Dairy                    49
Frozen Foods             49
Baking Goods             43
Canned                   38
Meat                     32
Health and Hygiene       30
Soft Drinks              26
Others                   17
Breads                   16
Breakfast                10
Hard Drinks               8
Seafood                   6
Starchy Foods             4
Name: Item_Type, dtype: int64

Or,

In [54]:
gp=df.groupby('Outlet_Identifier')

In [61]:
value=gp['Item_Type'].value_counts()
value

Outlet_Identifier  Item_Type
OUT010             Fruits and Vegetables    79
                   Snack Foods              71
                   Household                67
                   Frozen Foods             54
                   Dairy                    43
                                            ..
OUT049             Breads                   25
                   Others                   17
                   Starchy Foods            17
                   Breakfast                13
                   Seafood                   7
Name: Item_Type, Length: 160, dtype: int64

Findout maximum repeated Outlety_type in each outlet_location_type

In [84]:
olt=df.groupby('Outlet_Location_Type')

In [85]:
ot_value=olt['Outlet_Type'].value_counts()

In [95]:
ot_value

Outlet_Location_Type  Outlet_Type
Tier 1                Supermarket Type1    1860
                      Grocery Store         528
Tier 2                Supermarket Type1    2785
Tier 3                Supermarket Type3     935
                      Supermarket Type1     932
                      Supermarket Type2     928
                      Grocery Store         555
Name: Outlet_Type, dtype: int64

Which Outlet_type having highest sales in a perticular year

In [99]:
group_by_outlet_type=df.groupby('Outlet_Type')

In [108]:
item_olt_sales=group_by_outlet_type['Item_Outlet_Sales']

In [109]:
item_olt_sales

In [110]:
groupby_OEY=df.groupby('Outlet_Establishment_Year')

In [122]:
a=groupby_OEY['Outlet_Type']