 Grouping and aggregating means that to combining multiple pieces of datata into single result of data 
 
 Aggregate functions are like  min(), max(), mean(),median(),mode() etc.

In [1]:
import pandas as pd

In [2]:
survey_df=pd.read_csv('E:\Aroha Tech\Pandas Session\Pandas\Developer Survey 2020\survey_results_public.csv', index_col='Respondent')

schema_df=pd.read_csv('E:\Aroha Tech\Pandas Session\Pandas\Developer Survey 2020\survey_results_schema.csv', index_col="Column")

In [25]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [27]:
schema_df

                                                                   QuestionText
Column
Respondent                    Randomized respondent ID number (not in order ...
MainBranch                    Which of the following options best describes ...
Hobbyist                                                Do you code as a hobby?
Age                           What is your age (in years)? If you prefer not...
Age1stCode                    At what age did you write your first line of c...
CompFreq                       Is that compensation weekly, monthly, or yearly?
CompTotal                     What is your current total compensation (salar...
ConvertedComp                 Salary converted to annual USD salaries using ...
Country                                                      Where do you live?
CurrencyDesc                  Which currency do you use day-to-day? If your ...
CurrencySymbol                Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear        Which database environments have you done exte...
DatabaseWorkedWith            Which database environments have you done exte...
DevType                       Which of the following describe you? Please se...
EdLevel                       Which of the following best describes the high...
Employment                    Which of the following best describes your cur...
Ethnicity                     Which of the following describe you, if any? P...
Gender                        Which of the following describe you, if any? P...
JobFactors                    Imagine that you are deciding between two job ...
JobSat                        How satisfied are you with your current job? (...
JobSeek                       Which of the following best describes your cur...
LanguageDesireNextYear        Which programming, scripting, and markup langu...
LanguageWorkedWith            Which programming, scripting, and markup langu...
MiscTechDesireNextYear        Which other frameworks, libraries, and tools h...
MiscTechWorkedWith            Which other frameworks, libraries, and tools h...
NEWCollabToolsDesireNextYear  Which collaboration tools have you done extens...
NEWCollabToolsWorkedWith      Which collaboration tools have you done extens...
NEWDevOps                     Does your company have a dedicated DevOps person?
NEWDevOpsImpt                 How important is the practice of DevOps to sca...
NEWEdImpt                     How important is a formal education, such as a...
NEWJobHunt                    In general, what drives you to look for a new ...
NEWJobHuntResearch            When job searching, how do you learn more abou...
NEWLearn                      How frequently do you learn a new language or ...
NEWOffTopic                   Do you think Stack Overflow should relax restr...
NEWOnboardGood                Do you think your company has a good onboardin...
NEWOtherComms                 Are you a member of any other online developer...
NEWOvertime                   How often do you work overtime or beyond the f...
NEWPurchaseResearch           When buying a new tool or software, how do you...
NEWPurpleLink                 You search for a coding solution online and th...
NEWSOSites                    Which of the following Stack Overflow sites ha...
NEWStuck                      What do you do when you get stuck on a problem...
OpSys                         What is the primary operating system in which ...
OrgSize                       Approximately how many people are employed by ...
PlatformDesireNextYear        Which platforms have you done extensive develo...
PlatformWorkedWith            Which platforms have you done extensive develo...
PurchaseWhat                  What level of influence do you, personally, ha...
Sexuality                     Which of the following describe you, if any? P...
SOAccount                                 Do you have a Stack Overflow account?
SOComm                        Do you consider yourself a member of the Stack...
SOPartFreq                    How frequently would you say you participate i...
SOVisitFreq                   How frequently would you say you visit Stack O...
SurveyEase                    How easy or difficult was this survey to compl...
SurveyLength                  How do you feel about the length of the survey...
Trans                                                      Are you transgender?
UndergradMajor                            What was your primary field of study?
WebframeDesireNextYear        Which web frameworks have you done extensive d...
WebframeWorkedWith            Which web frameworks have you done extensive d...
WelcomeChange                 Compared to last year, how welcome do you feel...
WorkWeekHrs                   On average, how many hours per week do you wor...
YearsCode                     Including any education, how many years have y...
YearsCodePro                  NOT including education, how many years have y...

In [4]:
#Find median Salary 

survey_df['ConvertedComp'].median()

54049.0

In [6]:
# Find min salary

survey_df['ConvertedComp'].min()

0.0

In [7]:
# Find max salary

survey_df['ConvertedComp'].max()

2000000.0

In [8]:
# Find mean salary

survey_df['ConvertedComp'].mean()

103756.05014961446

In [11]:
# When we apply aggregate functions to a data farme, then it will going to look into our dataframe and find the columns that 

# contains numeric values and grab there median value

In [10]:
survey_df.median()

<ipython-input-10-a68720aaf70b>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  survey_df.median()

Age                 29.0
CompTotal        63000.0
ConvertedComp    54049.0
WorkWeekHrs         40.0
dtype: float64

# describe()

In [13]:
# If we want to see broad overview of our data or statical overview then we should go for describe() function

In [14]:
survey_df.describe()

                Age      CompTotal  ConvertedComp   WorkWeekHrs
count  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean      30.834111  3.190464e+242   1.037561e+05     40.782174
std        9.585392            inf   2.268853e+05     17.816383
min        1.000000   0.000000e+00   0.000000e+00      1.000000
25%       24.000000   2.000000e+04   2.464800e+04     40.000000
50%       29.000000   6.300000e+04   5.404900e+04     40.000000
75%       35.000000   1.250000e+05   9.500000e+04     44.000000
max      279.000000  1.111111e+247   2.000000e+06    475.000000

# count()

In [15]:
# count() function is use for count how many no. of non NaN rows

In [16]:
survey_df.count()

MainBranch                      64162
Hobbyist                        64416
Age                             45446
Age1stCode                      57900
CompFreq                        40069
CompTotal                       34826
ConvertedComp                   34756
Country                         64072
CurrencyDesc                    45472
CurrencySymbol                  45472
DatabaseDesireNextYear          44070
DatabaseWorkedWith              49537
DevType                         49370
EdLevel                         57431
Employment                      63854
Ethnicity                       45948
Gender                          50557
JobFactors                      49349
JobSat                          45194
JobSeek                         51727
LanguageDesireNextYear          54113
LanguageWorkedWith              57378
MiscTechDesireNextYear          42379
MiscTechWorkedWith              40314
NEWCollabToolsDesireNextYear    47287
NEWCollabToolsWorkedWith        52883
NEWDevOps                       42686
NEWDevOpsImpt                   41732
NEWEdImpt                       48465
NEWJobHunt                      42286
NEWJobHuntResearch              41022
NEWLearn                        56156
NEWOffTopic                     50804
NEWOnboardGood                  42623
NEWOtherComms                   57205
NEWOvertime                     43231
NEWPurchaseResearch             37321
NEWPurpleLink                   54803
NEWSOSites                      58275
NEWStuck                        54983
OpSys                           56228
OrgSize                         44334
PlatformDesireNextYear          50605
PlatformWorkedWith              53843
PurchaseWhat                    39364
Sexuality                       43992
SOAccount                       56805
SOComm                          56476
SOPartFreq                      46792
SOVisitFreq                     56970
SurveyEase                      51802
SurveyLength                    51701
Trans                           49345
UndergradMajor                  50995
WebframeDesireNextYear          40024
WebframeWorkedWith              42279
WelcomeChange                   52683
WorkWeekHrs                     41151
YearsCode                       57684
YearsCodePro                    46349
dtype: int64

In [17]:
# count a perticular column

survey_df['ConvertedComp'].count()

34756

# value_counts()

In [18]:
# count the individual value in a specific row and count the how many values in the column

In [20]:
survey_df['Hobbyist'].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

In [21]:
# Find how many people use which OS individually

In [28]:
survey_df['OpSys'].value_counts()

Windows        27170
Linux-based    14932
MacOS          14075
BSD               51
Name: OpSys, dtype: int64

In [29]:
# If we want to know how many people use esch os individually, then we should specify 'normalize=True' inside value_counts()

In [30]:
survey_df['OpSys'].value_counts(normalize=True)

Windows        0.483211
Linux-based    0.265562
MacOS          0.250320
BSD            0.000907
Name: OpSys, dtype: float64

# Grouping()

In [31]:
# A groupby() function involves some combinations of splits the objects, apply the function and combine the results.

In [33]:
survey_df.groupby(['Country'])    # it will split the countries

In [34]:
country_grp= survey_df.groupby(['Country'])

In [38]:
country_grp.get_group("United States")    # get_group() function grab the groupby() data

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,MongoDB,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Remote work options;Opportunities for professi...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",JavaScript,Python;SQL,Unity 3D,Ansible,NaN,Confluence;Jira;Github;Slack;Microsoft Teams;G...,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Linux-based,20 to 99 employees,iOS;Slack Apps and Integrations,Docker,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
14,I am a developer by profession,Yes,27.0,13,Yearly,66000.0,66000.0,United States,United States dollar,USD,Firebase;Microsoft SQL Server,Firebase;Microsoft SQL Server,"Developer, desktop or enterprise applications;...","Associate degree (A.A., A.S., etc.)",Employed full-time,White or of European descent,Man,Industry that I’d be working in;Flex time or a...,Slightly satisfied,"I’m not actively looking, but I am open to new...",HTML/CSS;JavaScript;SQL;TypeScript,HTML/CSS;JavaScript;SQL;TypeScript,Node.js,Node.js,Confluence;Jira;Github;Microsoft Teams;Google ...,Confluence;Jira;Github;Microsoft Teams,Yes,Extremely important,Somewhat important,Wanting to share accomplishments with a wider ...,"Read company media, such as employee blogs or ...",Every few months,No,Yes,No,Occasionally: 1-2 days per quarter but less th...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,100 to 499 employees,Google Cloud Platform;Raspberry Pi;Windows,Google Cloud Platform;Windows,I have little or no influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per week,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,Cassandra;Elasticsearch;MariaDB;PostgreSQL;Redis,Microsoft SQL Server;PostgreSQL,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Industry that I’d be working in;Languages, fra...",Slightly dissatisfied,"I’m not actively looking, but I am open to new...",C#;Go;Haskell;HTML/CSS;JavaScript;Python;Ruby;...,C#;HTML/CSS;JavaScript;Python;SQL;VBA,.NET Core;Teraform,.NET;Node.js,"Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",Github;Gitlab;Slack;Microsoft Teams;Google Sui...,Yes,Extremely important,Fairly important,Having a bad day (or week or month) at work;Be...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,No,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,20 to 99 employees,Docker;Kubernetes;Microsoft Azure,NaN,I have little or no influence,Straight / Heterosexual,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,USD,Elasticsearch;PostgreSQL;Redis;SQLite,Elasticsearch;MariaDB;MySQL;Redis;SQLite,"Developer, back-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;Perl,Bash/Shell/PowerShell;HTML/CSS;Perl,NaN,NaN,Github,Github;Slack,Not sure,Neutral,Very important,Looking to relocate,NaN,Once every few years,Yes,Onboarding? What onboarding?,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Do other work ...,Linux-based,100 to 499 employees,Linux,AWS;Linux,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58498,NaN,Yes,32.0,23,NaN,NaN,NaN,United States,NaN,NaN,Firebase;Microsoft SQL Server;MySQL;SQLite,Firebase;Microsoft SQL Server;MySQL;SQLite,"Data or business analyst;Developer, back-end;S...",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",White or of European descent,Man,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,.NET;.NET Core;Apache Spark;Cordova;Flutter;No...,.NET;.NET Core;Apache Spark;Cordova;Flutter;No...,Github;Gitlab;Facebook Workplace;Slack;Microso...,Github;Gitlab;Facebook Workplace;Slack;Microso...,NaN,NaN,Very important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Start a free trial;Visit developer communities...,Amused,Stack Exchange (public Q&A for a variety of to...,Watch help / tutorial videos;Visit another dev...,Linux-based,NaN,Android;Google Cloud Platform;Linux;MacOS;Micr...,Android;Google Cloud Platform;Linux;MacOS;Micr...,NaN,Straight / Heterosexual,NaN,NaN,NaN,NaN,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,NaN,NaN,8,Less than 1 year
58896,NaN,Yes,29.0,10,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,White or of European descent,Man,NaN,NaN,NaN,Haskell,Haskell,NaN,NaN,Gitlab;Slack,Github;Gitlab;Slack,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with;Visit develope...,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,MacOS,NaN,NaN,NaN,NaN,Gay or Lesbian;Queer,Yes,"Yes, somewhat",A few times per week,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,29,NaN
60931,NaN,Yes,NaN,17,NaN,NaN,NaN,United States,NaN,NaN,MariaDB;MySQL;PostgreSQL,MariaDB;MySQL,System administrator,Some college/university study without earning ...,Employed full-time,NaN,Man,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C#;C++;PHP;Python,Bash/Shell/PowerShell;HTML/CSS;PHP,Unity 3D;Unreal Engine,NaN,Github;Stack Overflow for Teams,Github,NaN,NaN,Not at all important/not necessary,NaN,NaN,NaN,Not sure,NaN,NaN,NaN,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Play games;Visit Stack Overflow;Watch help / t...,Linux-based,NaN,Android;Arduino;Linux;Raspberry Pi;Windows,WordPress,NaN,NaN,Yes,Neutral,I have never participated in Q&A on Stack Over...,Less than once per month or monthly,Neither easy nor difficult,Too long,No,Web development or web design,NaN,Drupal,Not applicable - I did not use Stack Overflow ...,NaN,5,NaN
63077,NaN,Yes,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,MySQL,MySQL,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,C++;Rust;SQL,C++;HTML/CSS;Java;JavaScript;Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,A few times per week,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year

In [39]:
# We can get same result by using filter

In [40]:
filt=survey_df['Country']=='United States'
survey_df.loc[filt]

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,MongoDB,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Remote work options;Opportunities for professi...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",JavaScript,Python;SQL,Unity 3D,Ansible,NaN,Confluence;Jira;Github;Slack;Microsoft Teams;G...,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Linux-based,20 to 99 employees,iOS;Slack Apps and Integrations,Docker,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
14,I am a developer by profession,Yes,27.0,13,Yearly,66000.0,66000.0,United States,United States dollar,USD,Firebase;Microsoft SQL Server,Firebase;Microsoft SQL Server,"Developer, desktop or enterprise applications;...","Associate degree (A.A., A.S., etc.)",Employed full-time,White or of European descent,Man,Industry that I’d be working in;Flex time or a...,Slightly satisfied,"I’m not actively looking, but I am open to new...",HTML/CSS;JavaScript;SQL;TypeScript,HTML/CSS;JavaScript;SQL;TypeScript,Node.js,Node.js,Confluence;Jira;Github;Microsoft Teams;Google ...,Confluence;Jira;Github;Microsoft Teams,Yes,Extremely important,Somewhat important,Wanting to share accomplishments with a wider ...,"Read company media, such as employee blogs or ...",Every few months,No,Yes,No,Occasionally: 1-2 days per quarter but less th...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,100 to 499 employees,Google Cloud Platform;Raspberry Pi;Windows,Google Cloud Platform;Windows,I have little or no influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per week,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,Cassandra;Elasticsearch;MariaDB;PostgreSQL;Redis,Microsoft SQL Server;PostgreSQL,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Industry that I’d be working in;Languages, fra...",Slightly dissatisfied,"I’m not actively looking, but I am open to new...",C#;Go;Haskell;HTML/CSS;JavaScript;Python;Ruby;...,C#;HTML/CSS;JavaScript;Python;SQL;VBA,.NET Core;Teraform,.NET;Node.js,"Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",Github;Gitlab;Slack;Microsoft Teams;Google Sui...,Yes,Extremely important,Fairly important,Having a bad day (or week or month) at work;Be...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,No,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,20 to 99 employees,Docker;Kubernetes;Microsoft Azure,NaN,I have little or no influence,Straight / Heterosexual,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,USD,Elasticsearch;PostgreSQL;Redis;SQLite,Elasticsearch;MariaDB;MySQL;Redis;SQLite,"Developer, back-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;Perl,Bash/Shell/PowerShell;HTML/CSS;Perl,NaN,NaN,Github,Github;Slack,Not sure,Neutral,Very important,Looking to relocate,NaN,Once every few years,Yes,Onboarding? What onboarding?,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Do other work ...,Linux-based,100 to 499 employees,Linux,AWS;Linux,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58498,NaN,Yes,32.0,23,NaN,NaN,NaN,United States,NaN,NaN,Firebase;Microsoft SQL Server;MySQL;SQLite,Firebase;Microsoft SQL Server;MySQL;SQLite,"Data or business analyst;Developer, back-end;S...",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",White or of European descent,Man,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,.NET;.NET Core;Apache Spark;Cordova;Flutter;No...,.NET;.NET Core;Apache Spark;Cordova;Flutter;No...,Github;Gitlab;Facebook Workplace;Slack;Microso...,Github;Gitlab;Facebook Workplace;Slack;Microso...,NaN,NaN,Very important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Start a free trial;Visit developer communities...,Amused,Stack Exchange (public Q&A for a variety of to...,Watch help / tutorial videos;Visit another dev...,Linux-based,NaN,Android;Google Cloud Platform;Linux;MacOS;Micr...,Android;Google Cloud Platform;Linux;MacOS;Micr...,NaN,Straight / Heterosexual,NaN,NaN,NaN,NaN,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,NaN,NaN,8,Less than 1 year
58896,NaN,Yes,29.0,10,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,White or of European descent,Man,NaN,NaN,NaN,Haskell,Haskell,NaN,NaN,Gitlab;Slack,Github;Gitlab;Slack,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with;Visit develope...,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,MacOS,NaN,NaN,NaN,NaN,Gay or Lesbian;Queer,Yes,"Yes, somewhat",A few times per week,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,29,NaN
60931,NaN,Yes,NaN,17,NaN,NaN,NaN,United States,NaN,NaN,MariaDB;MySQL;PostgreSQL,MariaDB;MySQL,System administrator,Some college/university study without earning ...,Employed full-time,NaN,Man,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C#;C++;PHP;Python,Bash/Shell/PowerShell;HTML/CSS;PHP,Unity 3D;Unreal Engine,NaN,Github;Stack Overflow for Teams,Github,NaN,NaN,Not at all important/not necessary,NaN,NaN,NaN,Not sure,NaN,NaN,NaN,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Play games;Visit Stack Overflow;Watch help / t...,Linux-based,NaN,Android;Arduino;Linux;Raspberry Pi;Windows,WordPress,NaN,NaN,Yes,Neutral,I have never participated in Q&A on Stack Over...,Less than once per month or monthly,Neither easy nor difficult,Too long,No,Web development or web design,NaN,Drupal,Not applicable - I did not use Stack Overflow ...,NaN,5,NaN
63077,NaN,Yes,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,MySQL,MySQL,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,C++;Rust;SQL,C++;HTML/CSS;Java;JavaScript;Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,A few times per week,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year

In [49]:
#Q Which os is using more in india
filt=survey_df['Country']=='India'
survey_df.loc[filt]['OpSys'].value_counts()

Windows        3426
Linux-based    2077
MacOS          1158
BSD               5
Name: OpSys, dtype: int64

In [52]:
#Other way
country_grp['OpSys'].value_counts().loc['India']

OpSys
Windows        3426
Linux-based    2077
MacOS          1158
BSD               5
Name: OpSys, dtype: int64

In [51]:
# To get all country wise

country_grp['OpSys'].value_counts()

Country      OpSys
Afghanistan  Windows        31
             Linux-based     8
             MacOS           5
Albania      Windows        24
             MacOS           7
                            ..
Zambia       MacOS           2
             Linux-based     1
Zimbabwe     Windows        18
             Linux-based     5
             MacOS           3
Name: OpSys, Length: 488, dtype: int64

In [54]:
# Display all countries median salary

country_grp['ConvertedComp'].median()

Country
Afghanistan                             15163.5
Albania                                 15900.0
Algeria                                  9432.0
Andorra                                 88640.0
Angola                                   5292.0
                                         ...
Venezuela, Bolivarian Republic of...     3600.0
Viet Nam                                10344.0
Yemen                                   36000.0
Zambia                                   5452.0
Zimbabwe                                 7200.0
Name: ConvertedComp, Length: 183, dtype: float64

In [55]:
# Display all countries max salary

country_grp['ConvertedComp'].max()

Country
Afghanistan                             1000000.0
Albania                                  194580.0
Algeria                                   36000.0
Andorra                                  141608.0
Angola                                     5736.0
                                          ...
Venezuela, Bolivarian Republic of...      24000.0
Viet Nam                                1000000.0
Yemen                                     36000.0
Zambia                                    60000.0
Zimbabwe                                 180000.0
Name: ConvertedComp, Length: 183, dtype: float64

In [56]:
# Display max salary of country India

country_grp['ConvertedComp'].max().loc['India']

1800000.0

In [57]:
# Display max salary of country India and United States

country_grp['ConvertedComp'].max().loc[['India','United States']]

Country
India            1800000.0
United States    2000000.0
Name: ConvertedComp, dtype: float64

# agg()

In [58]:
# display all countries min and max salary

In [59]:
country_grp['ConvertedComp'].agg(['min','max'])

                                          min        max
Country
Afghanistan                               0.0  1000000.0
Albania                                   0.0   194580.0
Algeria                                 300.0    36000.0
Andorra                               35672.0   141608.0
Angola                                 4848.0     5736.0
...                                       ...        ...
Venezuela, Bolivarian Republic of...     96.0    24000.0
Viet Nam                                  0.0  1000000.0
Yemen                                 36000.0    36000.0
Zambia                                  816.0    60000.0
Zimbabwe                               1200.0   180000.0

[183 rows x 2 columns]

In [60]:
# display  min and max salary of country India

country_grp['ConvertedComp'].agg(['min','max']).loc['India']

min          0.0
max    1800000.0
Name: India, dtype: float64

In [61]:
# display  min and max salary of country India and United States

country_grp['ConvertedComp'].agg(['min','max']).loc[['India','United States']]

               min        max
Country
India          0.0  1800000.0
United States  0.0  2000000.0

In [62]:
#Q Find the number of people knew the python in Country India

In [66]:
filt=survey_df['Country']=='India'
survey_df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()
# survey_df['LanguageWorkedWith']

2670

In [67]:
# Display the countywise how many people knew the python

In [71]:
country_grp= survey_df.groupby(['Country'])
country_grp['LanguageWorkedWith'].str.contains('Python').sum()  # 'SeriesGroupBy' object has no attribute 'str', 
                                                                    # So, we go for apply() method

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [72]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              11
Albania                                  13
Algeria                                  40
Andorra                                   3
Angola                                    1
                                       ...
Venezuela, Bolivarian Republic of...     29
Viet Nam                                102
Yemen                                     1
Zambia                                    4
Zimbabwe                                 13
Name: LanguageWorkedWith, Length: 183, dtype: int64

In [75]:
# Display the countywise how many % people knew the python

# country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [77]:
# for this we have to first count total no. of repondents for each country
country_respondents=survey_df['Country'].value_counts()
country_respondents

United States       12469
India                8403
United Kingdom       3896
Germany              3890
Canada               2191
                    ...
Kiribati                1
Nauru                   1
Lesotho                 1
Saint Lucia             1
Marshall Islands        1
Name: Country, Length: 183, dtype: int64

In [78]:
# Then now count total number of people who knew python

country_uses_pyhton= country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

country_uses_pyhton

Country
Afghanistan                              11
Albania                                  13
Algeria                                  40
Andorra                                   3
Angola                                    1
                                       ...
Venezuela, Bolivarian Republic of...     29
Viet Nam                                102
Yemen                                     1
Zambia                                    4
Zimbabwe                                 13
Name: LanguageWorkedWith, Length: 183, dtype: int64

In [79]:
# Now we combine tese two by Using concat() method

python_df=pd.concat([country_respondents,country_uses_pyhton], axis='columns', sort=False)

In [81]:
python_df

                  Country  LanguageWorkedWith
United States       12469                5964
India                8403                2670
United Kingdom       3896                1621
Germany              3890                1712
Canada               2191                1011
...                   ...                 ...
Kiribati                1                   0
Nauru                   1                   0
Lesotho                 1                   0
Saint Lucia             1                   1
Marshall Islands        1                   0

[183 rows x 2 columns]

In [84]:
python_df.rename(columns={'Country':'NumRespondents','LanguageWorkedWith':'NumknowsPython'}, inplace=True)

In [85]:
python_df

                  NumRespondents  NumknowsPython
United States              12469            5964
India                       8403            2670
United Kingdom              3896            1621
Germany                     3890            1712
Canada                      2191            1011
...                          ...             ...
Kiribati                       1               0
Nauru                          1               0
Lesotho                        1               0
Saint Lucia                    1               1
Marshall Islands               1               0

[183 rows x 2 columns]

In [86]:
# so finally here we calculate how many percentage people know python

#       percentage=part/whole * 100

python_df['PPKnowsPython']=(python_df['NumknowsPython']/python_df['NumRespondents']) * 100

In [87]:
python_df

                  NumRespondents  NumknowsPython  PPKnowsPython
United States              12469            5964      47.830620
India                       8403            2670      31.774366
United Kingdom              3896            1621      41.606776
Germany                     3890            1712      44.010283
Canada                      2191            1011      46.143314
...                          ...             ...            ...
Kiribati                       1               0       0.000000
Nauru                          1               0       0.000000
Lesotho                        1               0       0.000000
Saint Lucia                    1               1     100.000000
Marshall Islands               1               0       0.000000

[183 rows x 3 columns]

In [89]:
# sort the country by the largest percentage of people who know python

python_df.sort_values(by='PPKnowsPython', ascending=False, inplace=True)

In [90]:
python_df

,NumRespondents,NumknowsPython,PPKnowsPython
Gabon,1,1,100.000000
Saint Lucia,1,1,100.000000
"Micronesia, Federated States of...",1,1,100.000000
Montenegro,13,9,69.230769
Brunei Darussalam,3,2,66.666667
...,...,...,...
Monaco,2,0,0.000000
Niger,5,0,0.000000
Saint Vincent and the Grenadines,3,0,0.000000
Gambia,4,0,0.000000
Marshall Islands,1,0,0.000000