In [1]:
import boto3,os
import pandas as pd

In [2]:
s3=boto3.resource('s3')

In [6]:
s3.meta.client.upload_file(r'E:\Aroha Tech\AWS Session\s3 Bucket\15th Aug\vehicle_master.csv','som-aws-bucket-1','vehicle_master.csv')

In [8]:
import mysql.connector

In [10]:
con=mysql.connector.connect(host='localhost',database='test',user='root',password='root')
cursor=con.cursor()

In [11]:
cursor.execute(" create table vehicle_master(ID_VEHICLE int primary Key,REG_NUMBER varchar(50),NICK_NAME varchar(50),ID_BRANCH int,VEHICLE_TYPE varchar(100),MAKER varchar(50),MODEL varchar(50),PRODUCT_TYPE varchar(50)); ")
print("Table Created Successfully..")

Table Created Successfully..

In [ ]:
cursor.execute('alter table vehicle_master drop primary key;')

In [95]:
path='s3://som-aws-bucket-1/vehicle_master.csv'
data=pd.read_csv(path, header=None, names=['ID_VEHICLE','REG_NUMBER','NICK_NAME','ID_BRANCH','VEHICLE_TYPE','MAKER','MODEL','PRODUCT_TYPE'])

In [ ]:
type(data)

In [143]:
data.columns

Index(['ID_VEHICLE', 'REG_NUMBER', 'NICK_NAME', 'ID_BRANCH', 'VEHICLE_TYPE',
       'MAKER', 'MODEL', 'PRODUCT_TYPE'],
      dtype='object')

In [146]:
data

,ID_VEHICLE,REG_NUMBER,NICK_NAME,ID_BRANCH,VEHICLE_TYPE,MAKER,MODEL,PRODUCT_TYPE
0,343,XYZ 2899,2899,8,RC - Single Axle,TATA,1210,Tanker
1,330,AB 70 3099,3099,8,AV - Triple Axle(14 Tyres),AL,"3518 IL-18,7,12,8",Tanker
2,332,AB 70 3499,3499,8,RC - Triple Axle,TATA,"3118TC-16,7,10,7",Tanker
3,331,AB 70 3599,3599,8,RC - Triple Axle,TATA,"3118TC-16,7,10,7",Tanker
4,266,AB 30 A 0599,A 0599,8,RC - Double Axle,AL,2214/1,Tanker
...,...,...,...,...,...,...,...,...
170,283,AB 30 P 4699,P 4699,8,RC - Double Axle,TATA,2515 TCIC,Tanker
171,285,AB 30 P 4799,P 4799,8,RC - Double Axle,TATA,2515 TCIC,Tanker
172,286,AB 30 P 4899,P 4899,8,RC - Double Axle,TATA,2515 TCIC,Tanker
173,284,AB 30 P 5899,P 5899,8,RC - Double Axle,TATA,2515 TCIC,Tanker
174,294,CD 9U 299,U 299,8,AV - Triple Axle(14 Tyres),AL,"3516/Hino-10,7,12,8",LPG

In [144]:
for (row,rs) in data.iterrows():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174

In [114]:
for (row,rs) in data.iterrows():
    ID_VEHICLE=str(int(rs[0]))
    REG_NUMBER=rs[1]
    NICK_NAME=rs[2]
    ID_BRANCH=str(int(rs[3]))
    VEHICLE_TYPE=rs[4]
    MAKER=rs[5]
    MODEL=rs[6]
    PRODUCT_TYPE=rs[7]
    
    query=" insert into vehicle_master values(ID_VEHICLE,REG_NUMBER,NICK_NAME,ID_BRANCH,VEHICLE_TYPE,MAKER,MODEL,PRODUCT_TYPE) "
    
    cursor.execute(query)
con.commit()
cursor.close()

True

In [134]:
con=mysql.connector.connect(host='localhost',database='test',user='root',password='root')
cursor=con.cursor()

In [135]:
cursor.execute("select * from vehicle_master")

In [136]:
tdata=cursor.fetchall()

In [138]:
for row in tdata:
    print(row)

(0, None, None, None, None, None, None, None)
(205, 'AB 30 AC 1599', 'AC 1599', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/412-15,7,10,8', 'Tanker')
(208, 'AB 30 AB 1399', 'AB 1399', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/Hino-10,7,12,8', 'Tanker')
(210, 'AB 30 AA 6999', 'AA 6999', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/Hino-10,7,12,8', 'Tanker')
(213, 'AB 30 AB 1499', 'AB 1499', 8, 'AV - Triple Axle(14 Tyres)', 'TATA', '3516TC-16,7,10,8', 'Tanker')
(214, 'AB 30AB 1599', 'AB 1599', 8, 'AV - Triple Axle(14 Tyres)', 'TATA', '3516TC-16,7,10,8', 'Tanker')
(220, 'AB 30 AB 1699', 'AB 1699', 8, 'AV - Triple Axle(14 Tyres)', 'TATA', '3516TC-16,7,10,8', 'Tanker')
(222, 'AB 30 AA 6899', 'AA 6899', 8, 'AV - Triple Axle(14 Tyres)', 'TATA', '3516TC-16,7,10,8', 'Tanker')
(223, 'AB 30 AF 4799', 'AF 4799', 8, 'RC - Double Axle', 'AL', '2214/1', 'Tanker')
(224, 'AB 30 AF 6799 ', 'AF 6799', 8, 'RC - Double Axle', 'TATA', '2515TC', 'Tanker')
(255, 'AB 30 AA 3399', 'AA 3399', 8, 'RC - Double Axle', 'TATA', '2515 TCIC', 'Tanker')
(256, 'AB 30 AB 1299', 'AB 1299', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/Hino-10,7,12,8', 'Tanker')
(257, 'AB 30 AA 2299', 'AA 2299', 8, 'RC - Double Axle', 'TATA', '2515 TCIC', 'Tanker')
(258, 'AB 30 AA 2499', 'AA 2499', 8, 'RC - Double Axle', 'TATA', '2515 TCIC', 'Tanker')
(259, 'AB 30 AA 2399', 'AA 2399', 8, 'RC - Double Axle', 'TATA', '2515 TCIC', 'Tanker')
(260, 'AB 30 AA 0099', 'AA 0099', 8, 'AV - Triple Axle(14 Tyres)', 'TATA', '3516TC-16,7,10,8', 'Tanker')
(264, 'AB 30AD 2299', 'AD 2299', 8, 'RC - Double Axle', 'AL', '2214/1S-10,7,10,4', 'Tanker')
(266, 'AB 30 A 0599', 'A 0599', 8, 'RC - Double Axle', 'AL', '2214/1', 'Tanker')
(268, 'AB 30AD 2399', 'AD 2399', 8, 'RC - Double Axle', 'AL', '2214/1', 'Tanker')
(278, 'AB 30 AC 7899', 'AC 7899', 8, 'AV - Triple Axle(14 Tyres)', 'TATA', '3516TC-16,7,10,8', 'Tanker')
(290, 'AB 30A 0699', 'A 0699', 8, 'RC - Double Axle', 'TATA', '2213', 'Tanker')
(291, 'AB 30AE 3699', 'AE 3699', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/Hino-10,7,12,8', 'Tanker')
(292, 'AB 30 AB 1899', 'AB 1899', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/Hino-10,7,12,8', 'Tanker')
(297, 'AB 30 AB 0499', 'AB 0499', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/Hino-10,7,12,8', 'LPG')
(330, 'AB 70 3099', '3099', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3518 IL-18,7,12,8', 'Tanker')
(331, 'AB 70 3599', '3599', 8, 'RC - Triple Axle', 'TATA', '3118TC-16,7,10,7', 'Tanker')
(332, 'AB 70 3499', '3499', 8, 'RC - Triple Axle', 'TATA', '3118TC-16,7,10,7', 'Tanker')
(337, 'AB 30 AD 7899', 'AD 7899', 8, 'Four Wheeler', 'TATA', 'Magic', 'Four Wheeler')
(343, 'XYZ 2899', '2899', 8, 'RC - Single Axle', 'TATA', '1210', 'Tanker')
(557, 'BC 01 AE 4499', 'AE 4499', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(558, 'BC 01 AE 8999', 'AE 8999', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(563, 'BC 01 AE 5699', 'AE 5699', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(564, 'BC 01 AE 3469', 'AE 3469', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(565, 'BC 01 AE 2699', 'AE 2699', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(570, 'BC 01 AE 4679', 'AE 4679', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(574, 'BC 01 AE 6689', 'AE 6689', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(575, 'BC 05 AF 2899', 'AF 2899', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(576, 'BC 05 AF 2999', 'AF 2999', 8, 'RC - Triple Axle', 'BHARAT BENZ', '3123 Rigid (8x2)-TL', 'Tanker')
(608, 'AB 30 AA 2063', 'AA 2063', 8, 'AV - Triple Axle(14 Tyres)', 'AL', '3516/412-15,7,10,8', 'Tanker')
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)
(0, None, None, None, None, None, None, None)

0

In [42]:
s3_client=boto3.client('s3')

In [52]:
obj=s3_client.get_object(Bucket='som-aws-bucket-1',Key='vehicle_master.csv')

In [53]:
file_data=pd.read_csv(obj['Body'])

In [54]:
print(file_data)

     343       XYZ 2899    2899  8            RC - Single Axle  TATA  \
0    330     AB 70 3099    3099  8  AV - Triple Axle(14 Tyres)    AL
1    332     AB 70 3499    3499  8            RC - Triple Axle  TATA
2    331     AB 70 3599    3599  8            RC - Triple Axle  TATA
3    266   AB 30 A 0599  A 0599  8            RC - Double Axle    AL
4    290    AB 30A 0699  A 0699  8            RC - Double Axle  TATA
..   ...            ...     ... ..                         ...   ...
169  283   AB 30 P 4699  P 4699  8            RC - Double Axle  TATA
170  285   AB 30 P 4799  P 4799  8            RC - Double Axle  TATA
171  286   AB 30 P 4899  P 4899  8            RC - Double Axle  TATA
172  284  AB 30 P 5899   P 5899  8            RC - Double Axle  TATA
173  294      CD 9U 299   U 299  8  AV - Triple Axle(14 Tyres)    AL

                    1210  Tanker
0      3518 IL-18,7,12,8  Tanker
1       3118TC-16,7,10,7  Tanker
2       3118TC-16,7,10,7  Tanker
3                 2214/1  Tanker
4                   2213  Tanker
..                   ...     ...
169            2515 TCIC  Tanker
170            2515 TCIC  Tanker
171            2515 TCIC  Tanker
172            2515 TCIC  Tanker
173  3516/Hino-10,7,12,8     LPG

[174 rows x 8 columns]

In [67]:
with open('file_data', 'r') as f:
    rows=csv.reader(f, delimiter=',')
    values=[]
    for row in rows:
        value=(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7])
        values.append(value)

FileNotFoundError: [Errno 2] No such file or directory: 'file_data'